'use strict'; // code generated by pbf v3.2.1

// Message ========================================

var Message = exports.Message = {};

Message.read = function (pbf, end) {
    return pbf.readFields(Message._readField, {message: "", username: ""}, end);
};
Message._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.message = pbf.readString();
    else if (tag === 2) obj.username = pbf.readString();
};
Message.write = function (obj, pbf) {
    if (obj.message) pbf.writeStringField(1, obj.message);
    if (obj.username) pbf.writeStringField(2, obj.username);
};

// State ========================================

var State = exports.State = {};

State.read = function (pbf, end) {
    return pbf.readFields(State._readField, {isWriting: false}, end);
};
State._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.isWriting = pbf.readBoolean();
};
State.write = function (obj, pbf) {
    if (obj.isWriting) pbf.writeBooleanField(1, obj.isWriting);
};

// HeartBeat ========================================

var HeartBeat = exports.HeartBeat = {};

HeartBeat.read = function (pbf, end) {
    return pbf.readFields(HeartBeat._readField, {username: "", state: null}, end);
};
HeartBeat._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.username = pbf.readString();
    else if (tag === 2) obj.state = State.read(pbf, pbf.readVarint() + pbf.pos);
};
HeartBeat.write = function (obj, pbf) {
    if (obj.username) pbf.writeStringField(1, obj.username);
    if (obj.state) pbf.writeMessage(2, State.write, obj.state);
};
